"use client";

import React, { useContext } from "react";
import { AuthContext } from "@/providers/AuthProvider";

const PrintReportTemplate = React.forwardRef(({ title, subtitle, dateRange, children }, ref) => {
  const { user, company } = useContext(AuthContext);

  return (
    <div ref={ref} className="p-8 bg-white text-black font-sans w-full print-layout" style={{ color: "#000" }}>
      <style jsx global>{`
        @media print {
          body {
            background: white !important;
            color: black !important;
          }
          .print-layout {
            padding: 20px !important;
            color: #000 !important;
          }
          .print-table {
            width: 100% !important;
            border-collapse: collapse !important;
          }
          .print-table th {
            background-color: #f3f4f6 !important;
            color: #000 !important;
            border: 1px solid #d1d5db !important;
            padding: 8px !important;
            font-weight: bold !important;
            font-size: 11px !important;
          }
          .print-table td {
            border: 1px solid #e5e7eb !important;
            padding: 8px !important;
            font-size: 11px !important;
            color: #000 !important;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>

      {/* Letterhead (Pad) */}
      <div className="flex items-start justify-between border-b-2 border-gray-800 pb-4 mb-6">
        <div className="flex items-center gap-4">
          {company?.logo ? (
            <img src={company.logo} alt="Logo" className="w-16 h-16 object-contain" />
          ) : (
            <div className="w-16 h-16 bg-gray-150 flex items-center justify-center font-bold text-xl rounded border border-gray-300">
              CR
            </div>
          )}
          <div>
            <h1 className="text-2xl font-extrabold tracking-tight text-gray-900">{company?.name || "Chayatol Resort & Restaurant"}</h1>
            <p className="text-xs text-gray-700 mt-1">{company?.address}</p>
            <p className="text-xs text-gray-700">Phone: {company?.phone} | Email: {company?.email}</p>
            {company?.website && <p className="text-xs text-gray-700">Website: {company.website}</p>}
          </div>
        </div>
        <div className="text-right text-xs text-gray-700">
          {company?.binNumber && <p><span className="font-bold">BIN:</span> {company.binNumber}</p>}
          {company?.tinNumber && <p><span className="font-bold">TIN:</span> {company.tinNumber}</p>}
          {company?.otherInformation && <p className="mt-1 italic">{company.otherInformation}</p>}
        </div>
      </div>

      {/* Report Info */}
      <div className="mb-6">
        <h2 className="text-lg font-bold uppercase tracking-wider text-gray-900">{title}</h2>
        {subtitle && <p className="text-sm text-gray-600 font-medium mt-1">{subtitle}</p>}
        <div className="flex justify-between items-center text-xs text-gray-600 mt-3 border-t border-b border-gray-250 py-2">
          <div>
            {dateRange && <p><span className="font-semibold text-gray-800">Period:</span> {dateRange}</p>}
          </div>
          <div className="text-right">
            <p><span className="font-semibold text-gray-800">Generated on:</span> {new Date().toLocaleString("en-GB")}</p>
            <p><span className="font-semibold text-gray-800">Generated by:</span> {user?.name || "System"}</p>
          </div>
        </div>
      </div>

      {/* Main Table / Children */}
      <div className="print-content w-full mb-12">
        {children}
      </div>

      {/* Signatures */}
      <div className="mt-16 pt-8 border-t border-gray-300 flex justify-between text-xs text-gray-500">
        <div className="text-center w-40">
          <div className="border-b border-gray-400 h-10 w-full mb-1"></div>
          <p className="font-semibold">Prepared By</p>
        </div>
        <div className="text-center w-40">
          <div className="border-b border-gray-400 h-10 w-full mb-1"></div>
          <p className="font-semibold">Verified By</p>
        </div>
        <div className="text-center w-40">
          <div className="border-b border-gray-400 h-10 w-full mb-1"></div>
          <p className="font-semibold">Authorized Signature</p>
        </div>
      </div>
    </div>
  );
});

PrintReportTemplate.displayName = "PrintReportTemplate";

export default PrintReportTemplate;
